/**:
  ros__parameters:
    particle_filter:
      num_particles: 100000
      update_interval: 0.1        # seconds
      initial_max_speed: 20.0
      observation_sigma: 100.0
      decay_factor: 0.95
      min_resample_speed: 3.0
      noise_std_pos: 0.1
      noise_std_yaw: 0.4
      noise_std_yaw_rate: 1.0
      noise_std_speed: 4.0
    particle_filter_statistics:
      frame_id: map
      resolution: 1.0
      pub_interval: 1.0           # seconds
    filter:
      near_clutter_range: 0.0
    map:
      frame_id: map
      length: 2000.0              # meters
      width: 2000.0               # meters
      resolution: 1.0
      pub_interval: 0.1           # seconds
    max_queue_size: 1000
