grid_map_visualization:
  ros__parameters:
    grid_map_topic: /aura/perception/sensors/halo_a/particle_filter_statistics

    grid_map_visualizations: [occupancy_grid]

    occupancy_grid:
        type: occupancy_grid
        params:
          layer: pf_statistics
          data_min: 0.0
          data_max: 1.0
