/**:
  ros__parameters:
    filter:
      near_clutter_range: 0.0
    map:
      frameId: map
      length: 1500.0
      width: 1500.0
      pub_interval: 0.10000000149011612
      resolution: 1.0
      width: 1500.0
    max_queue_size: 1000
