/**:
  ros__parameters:
    filter:
      near_clutter_range: 0.0
    map:
      frameId: map
      length: 1500.0              # meters
      width: 1500.0               # meters
      resolution: 1.0
      pub_interval: 0.1           # seconds
    max_queue_size: 1000
